### PR TITLE
Add `fill/1` macro for filling an expression `_` placeholders.

### PR DESCRIPTION
**Pull request by vic**
Inspired by `op/1` I made a generalized macro `fill/1` that can
be used to fill any `_` placeholder in an expression arguments
(see the doctests for examples).

@aleandros maybe `fill/1` could replace `op/1` dont you think?

### CODE REVIEW

**Comment by aleandros** [comment]
Love it! Yes, this *must* replace `op/1` completely. But I feel like I have to ask, why curry by default? I think it's awesome, but what would be the rationale?

As a side note, inspiration for `op/1` came directly from Scala's placeholder syntax. It's pretty awesome.

**Comment by vic** [comment]
Well, just felt like currying was the natural thing to do, didn't have any particular reason, just felt like `Sky`'s preferred way was curried-functions. We can make it just return the non-curried function if you like it more :) and let the user explicitly curry it when needed.

**Comment by aleandros** [comment]
Nah, I believe it's a safe bet to keep curry by default, specially since `uncurry/2` is already present.
Could you do me a favor and rebase on top of the latest commit at the original branch, just to keep it clean. Thanks a lot for all your contributions man! You rock.

**Comment by vic** [comment]
sure, shall we remove `op/1` then?

**Comment by aleandros** [comment]
Yep! But I can do that if you're short on time. No worries

**Comment by vic** [comment]
rebased.

**Comment by aleandros** [comment]
Doh! I was about to rebase when I found out there's already a "Rebase and Merge" action. ¯\_(ツ)_/¯ sorry

**Pull request merged**
